package Viewer;


import modeloDados.ClassDados;
import modeloBeans.ClassParametros;

public class FormPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FormPrincipal
     */
    public FormPrincipal() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        LabelUsuariologado = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        MenuCadastros = new javax.swing.JMenu();
        MenuItemCadastroUsuario = new javax.swing.JMenuItem();
        jMenuItemCadastroProduto = new javax.swing.JMenuItem();
        MenuConsulta = new javax.swing.JMenu();
        MenuItemUsuario = new javax.swing.JMenuItem();
        jMenuItemProduto = new javax.swing.JMenuItem();
        MenuSistema = new javax.swing.JMenu();
        MenuItemParametros = new javax.swing.JMenuItem();
        MenuItemTrocaUsuario = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Usuario:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelUsuariologado, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 294, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(LabelUsuariologado, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MenuCadastros.setMnemonic('f');
        MenuCadastros.setText("Cadastros");
        MenuCadastros.setEnabled(false);

        MenuItemCadastroUsuario.setText("Usuario");
        MenuItemCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemCadastroUsuarioActionPerformed(evt);
            }
        });
        MenuCadastros.add(MenuItemCadastroUsuario);

        jMenuItemCadastroProduto.setText("Produto");
        jMenuItemCadastroProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadastroProdutoActionPerformed(evt);
            }
        });
        MenuCadastros.add(jMenuItemCadastroProduto);

        menuBar.add(MenuCadastros);

        MenuConsulta.setMnemonic('e');
        MenuConsulta.setText("Consulta");
        MenuConsulta.setEnabled(false);

        MenuItemUsuario.setText("Usuario");
        MenuItemUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemUsuarioActionPerformed(evt);
            }
        });
        MenuConsulta.add(MenuItemUsuario);

        jMenuItemProduto.setText("Produto");
        jMenuItemProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProdutoActionPerformed(evt);
            }
        });
        MenuConsulta.add(jMenuItemProduto);

        menuBar.add(MenuConsulta);

        MenuSistema.setText("Sistema");

        MenuItemParametros.setText("Parametros");
        MenuItemParametros.setEnabled(false);
        MenuItemParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemParametrosActionPerformed(evt);
            }
        });
        MenuSistema.add(MenuItemParametros);

        MenuItemTrocaUsuario.setText("Trocar de usuario");
        MenuItemTrocaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuItemTrocaUsuarioActionPerformed(evt);
            }
        });
        MenuSistema.add(MenuItemTrocaUsuario);

        menuBar.add(MenuSistema);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 265, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuItemCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemCadastroUsuarioActionPerformed
        FrameCadastroUsuario novousuario = new FrameCadastroUsuario();
        novousuario.setVisible(true);
    }//GEN-LAST:event_MenuItemCadastroUsuarioActionPerformed

    private void MenuItemParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemParametrosActionPerformed
        FrameParametros frameparametros = new FrameParametros();
        frameparametros.setVisible(true);
    }//GEN-LAST:event_MenuItemParametrosActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        ClassParametros parametro = new ClassParametros();
        LabelUsuariologado.setText(ClassDados.getUsuario());
        MenuItemParametros.setEnabled((parametro.isMenuParametros(ClassDados.getNivelAcesso())));
        MenuCadastros.setEnabled(parametro.isMenuCadastro(ClassDados.getNivelAcesso()));
        MenuConsulta.setEnabled(parametro.isMenuConsulta(ClassDados.getNivelAcesso()));
        MenuSistema.setEnabled(parametro.isMenuSistema(ClassDados.getNivelAcesso()));
    }//GEN-LAST:event_formWindowOpened

    private void MenuItemTrocaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemTrocaUsuarioActionPerformed
        FrameLogin framelogin = new FrameLogin();
        framelogin.setVisible(true);
        dispose();
    }//GEN-LAST:event_MenuItemTrocaUsuarioActionPerformed

    private void MenuItemUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuItemUsuarioActionPerformed
        FrameConsultaUsuarios frameconsultausuario = new FrameConsultaUsuarios();
        frameconsultausuario.setVisible(true);
    }//GEN-LAST:event_MenuItemUsuarioActionPerformed

    private void jMenuItemCadastroProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadastroProdutoActionPerformed
        FrameCadastroProduto framecadastroproduto = new FrameCadastroProduto();
        framecadastroproduto.setVisible(true);
    }//GEN-LAST:event_jMenuItemCadastroProdutoActionPerformed

    private void jMenuItemProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProdutoActionPerformed
         FrameConsultaProduto consultaProduto = new FrameConsultaProduto();
        consultaProduto.setVisible(true);
    }//GEN-LAST:event_jMenuItemProdutoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPrincipal().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelUsuariologado;
    private javax.swing.JMenu MenuCadastros;
    private javax.swing.JMenu MenuConsulta;
    private javax.swing.JMenuItem MenuItemCadastroUsuario;
    private javax.swing.JMenuItem MenuItemParametros;
    private javax.swing.JMenuItem MenuItemTrocaUsuario;
    private javax.swing.JMenuItem MenuItemUsuario;
    private javax.swing.JMenu MenuSistema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuItem jMenuItemCadastroProduto;
    private javax.swing.JMenuItem jMenuItemProduto;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
